version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: itaccess-db
    restart: always
    environment:
      POSTGRES_DB: itaccessdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  backend:
    build: .
    container_name: itaccess-backend
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/itaccessdb
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - APP_JWT_SECRET=votre_secret_tres_long_et_securise_ici
      - APP_UPLOAD_ATTACHMENTS_DIR=/app/uploads/attachments
    volumes:
      - ./uploads:/app/uploads