ALTER TABLE IF EXISTS tests ADD COLUMN IF NOT EXISTS resolved BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE IF EXISTS test_steps ADD COLUMN IF NOT EXISTS resolved BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE test_sessions ADD COLUMN IF NOT EXISTS plateforme VARCHAR(10) DEFAULT 'Web' NOT NULL;
